# Generated by Django 5.2 on 2025-07-09 16:08

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('bio_title', models.CharField(max_length=200, verbose_name='Заголовок биографии')),
                ('bio_content', models.TextField(verbose_name='Содержание биографии')),
                ('photo', models.ImageField(blank=True, upload_to='about/', verbose_name='Фото')),
                ('skills', models.TextField(verbose_name='Навыки и технологии')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('resume_pdf', models.FileField(blank=True, help_text='Загрузите ваше резюме в формате PDF', upload_to='resume/', verbose_name='Резюме (PDF)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255, verbose_name='Учебное заведение')),
                ('degree', models.CharField(max_length=255, verbose_name='Степень/Специальность')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='Направление обучения')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущее место учебы')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_items', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение сертификата')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='Файл сертификата')),
                ('date_received', models.DateField(verbose_name='Дата получения')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание обязанностей')),
                ('technologies', models.CharField(blank=True, max_length=500, verbose_name='Используемые технологии')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущее место работы')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название проекта (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название проекта (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('technology', models.CharField(max_length=200, verbose_name='Технологии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/%Y/%m/%d/', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Часть URL-адреса (должен быть уникальным в рамках языка)', max_length=200, verbose_name='URL-идентификатор')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('translation_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='portfolio.project', verbose_name='Связанный перевод')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_date'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'language'), name='unique_slug_per_language_project')],
            },
        ),
    ]
