# Generated by Django 5.2 on 2025-07-09 16:36

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=markdownx.models.MarkdownxField(verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=markdownx.models.MarkdownxField(verbose_name='Описание (RU)'),
        ),
    ]
