# Generated by Django 5.2 on 2025-11-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Год')),
                ('tech_stack_ru', models.TextField(verbose_name='Технологический стек (RU)')),
                ('tech_stack_en', models.TextField(verbose_name='Технологический стек (EN)')),
                ('business_results_ru', models.TextField(verbose_name='Бизнес-результаты (RU)')),
                ('business_results_en', models.TextField(verbose_name='Бизнес-результаты (EN)')),
                ('key_competencies_ru', models.TextField(verbose_name='Ключевые компетенции (RU)')),
                ('key_competencies_en', models.TextField(verbose_name='Ключевые компетенции (EN)')),
                ('summary_ru', models.TextField(verbose_name='Краткое резюме (RU)')),
                ('summary_en', models.TextField(verbose_name='Краткое резюме (EN)')),
            ],
            options={
                'verbose_name': 'Достижения за год',
                'verbose_name_plural': 'Достижения по годам',
                'ordering': ['-year'],
            },
        ),
    ]
