# Generated by Django 5.2 on 2025-11-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_yearachievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearachievements',
            name='projects_en',
            field=models.TextField(blank=True, verbose_name='Описание крупных проектов (EN)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='projects_ru',
            field=models.TextField(blank=True, verbose_name='Описание крупных проектов (RU)'),
        ),
    ]
