# Generated by Django 5.2 on 2025-11-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_yearachievements_projects_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearachievements',
            name='page_subtitle_en',
            field=models.CharField(blank=True, help_text='Например: System Integrator', max_length=200, verbose_name='Подзаголовок/Должность (EN)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='page_subtitle_ru',
            field=models.CharField(blank=True, help_text='Например: Системный интегратор', max_length=200, verbose_name='Подзаголовок/Должность (RU)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='page_title_en',
            field=models.CharField(blank=True, help_text='Например: Key Achievements for 2025. Oracle PL/SQL Developer', max_length=300, verbose_name='Заголовок страницы (EN)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='page_title_ru',
            field=models.CharField(blank=True, help_text='Например: Ключевые достижения за 2025 год. Oracle PL/SQL Developer', max_length=300, verbose_name='Заголовок страницы (RU)'),
        ),
    ]
