# Generated by Django 5.2 on 2025-11-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_yearachievements_page_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearachievements',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='Оптимально 150-160 символов', max_length=160, verbose_name='SEO Description (EN)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='meta_description_ru',
            field=models.CharField(blank=True, help_text='Оптимально 150-160 символов', max_length=160, verbose_name='SEO Description (RU)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='SEO Keywords (EN)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='SEO Keywords (RU)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Оптимально 50-60 символов. Если пусто, используется page_title', max_length=70, verbose_name='SEO Title (EN)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='Оптимально 50-60 символов. Если пусто, используется page_title', max_length=70, verbose_name='SEO Title (RU)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Рекомендуется 1200x630px для социальных сетей', null=True, upload_to='achievements/', verbose_name='Open Graph изображение'),
        ),
    ]
