# Generated by Django 5.2 on 2025-11-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_yearachievements_meta_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearachievements',
            name='learning_development_en',
            field=models.TextField(blank=True, verbose_name='Обучение и развитие (EN)'),
        ),
        migrations.AddField(
            model_name='yearachievements',
            name='learning_development_ru',
            field=models.TextField(blank=True, verbose_name='Обучение и развитие (RU)'),
        ),
    ]
