# Generated by Django 5.2.16 on 2026-07-15 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnkiNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('guid', models.CharField(blank=True, max_length=20, null=True)),
                ('order_num', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
                ('spanish', models.TextField(blank=True, null=True, verbose_name='Испанский')),
                ('russian', models.TextField(blank=True, null=True, verbose_name='Русский')),
                ('english', models.TextField(blank=True, null=True, verbose_name='Английский')),
                ('example_en_ru', models.TextField(blank=True, null=True, verbose_name='Пример EN-RU')),
                ('longman_sound', models.TextField(blank=True, null=True, verbose_name='Аудио Longman')),
                ('longman_example', models.TextField(blank=True, null=True, verbose_name='Пример Longman')),
                ('oxford_example', models.TextField(blank=True, null=True, verbose_name='Пример Oxford')),
                ('oxford_example_cloze', models.TextField(blank=True, null=True, verbose_name='Oxford cloze')),
                ('collocations', models.TextField(blank=True, null=True, verbose_name='Коллокации')),
                ('oxford_3000_cloze', models.TextField(blank=True, null=True, verbose_name='Oxford 3000 cloze')),
                ('oxford_definition', models.TextField(blank=True, null=True, verbose_name='Определение Oxford')),
                ('ipa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Транскрипция')),
                ('en_sound', models.TextField(blank=True, null=True, verbose_name='Аудио EN')),
                ('full_definition', models.TextField(blank=True, null=True, verbose_name='Полное определение')),
                ('homonym', models.TextField(blank=True, null=True, verbose_name='Омоним')),
                ('homophones', models.TextField(blank=True, null=True, verbose_name='Омофоны')),
                ('synonyms', models.TextField(blank=True, null=True, verbose_name='Синонимы')),
                ('word_family', models.TextField(blank=True, null=True, verbose_name='Семья слов')),
                ('common_error', models.TextField(blank=True, null=True, verbose_name='Ошибки')),
                ('irregular_verbs', models.TextField(blank=True, null=True, verbose_name='Непр. глаголы')),
                ('idioms_list', models.TextField(blank=True, null=True, verbose_name='Идиомы')),
                ('proverb', models.TextField(blank=True, null=True, verbose_name='Пословица')),
                ('portuguese', models.TextField(blank=True, null=True, verbose_name='Португальский')),
                ('french', models.TextField(blank=True, null=True, verbose_name='Французский')),
                ('german', models.TextField(blank=True, null=True, verbose_name='Немецкий')),
                ('idiom', models.TextField(blank=True, null=True, verbose_name='Идиома')),
                ('idiom_meaning', models.TextField(blank=True, null=True, verbose_name='Значение идиомы')),
                ('idiom_example', models.TextField(blank=True, null=True, verbose_name='Пример идиомы')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Карточка Anki',
                'verbose_name_plural': 'Карточки Anki',
                'db_table': 'anki_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.BigIntegerField(verbose_name='ID карточки')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='Фактор лёгкости')),
                ('interval', models.IntegerField(default=0, verbose_name='Интервал (дни)')),
                ('reps', models.IntegerField(default=0, verbose_name='Повторения')),
                ('lapses', models.IntegerField(default=0, verbose_name='Ошибки')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующее повторение')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='Последнее повторение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anki_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс карточки',
                'verbose_name_plural': 'Прогресс карточек',
                'ordering': ['next_review'],
                'indexes': [models.Index(fields=['user', 'next_review'], name='anki_cardpr_user_id_29630e_idx'), models.Index(fields=['user', '-reps'], name='anki_cardpr_user_id_278fdf_idx')],
                'unique_together': {('user', 'note_id')},
            },
        ),
    ]
